version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    ports:
      - "5432:5432"
  api:
    build: .
    depends_on:
      - db
    environment:
      ALLOW_CREDENTIALS: "true"
      ALLOWED_HEADERS: "*"
      ALLOWED_METHODS: "*"
      ALLOWED_ORIGINS: "*"
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      ENVIRONMENT: dev
    ports:
      - "8000:80"
    entrypoint: ["/app/compose-entrypoint.sh"]

volumes:
  postgres-data:
